// Generated by https://quicktype.io

import { User } from "./Request";


// Generated by https://quicktype.io

export interface Keycard {
    keycard_id: string;
    user_id: string;
    is_lost: boolean;
    is_locked: boolean;
    is_deactivated: boolean;
    is_given_back: boolean;
    request_id: string;
    given_out?: string;
}

