// Generated by https://quicktype.io

export interface Request {
    accept: boolean;
    changed_at: string;
    comments?: Comment[];
    created_at: string;
    description: string;
    door_group_id: string;
    pending: boolean;
    reject: boolean;
    request_id: string;
    requester_id: string;
    requester: User
}

export interface Comment {
    comment: string;
    comment_id: string;
    request_id: string;
    user: User;
    user_id: string;
    written_at: string;
}


export interface Role {
    description: string;
    name: string;
    role_id: string;
}

export interface User {
    user_id: string;
    name: string;
    role: Role;
    email: string;
    worker: Worker;
    is_leader: boolean;
    is_admin: boolean;
}



export interface Worker {
    user_id: string;
    boss: null;
}
