//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

pub mod prelude;

pub mod sea_orm_active_enums;
pub mod tbl_building;
pub mod tbl_department;
pub mod tbl_door;
pub mod tbl_door_to_request;
pub mod tbl_door_to_request_history;
pub mod tbl_keycard;
pub mod tbl_keycard_archive;
pub mod tbl_keycard_usage_history;
pub mod tbl_request;
pub mod tbl_request_archive;
pub mod tbl_request_comment;
pub mod tbl_request_department;
pub mod tbl_request_log;
pub mod tbl_room;
pub mod tbl_room_department;
pub mod tbl_user;
