//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub use super::tbl_building::Entity as TblBuilding;
pub use super::tbl_change_rights_history::Entity as TblChangeRightsHistory;
pub use super::tbl_department::Entity as TblDepartment;
pub use super::tbl_door::Entity as TblDoor;
pub use super::tbl_door_to_request::Entity as TblDoorToRequest;
pub use super::tbl_door_to_request_history::Entity as TblDoorToRequestHistory;
pub use super::tbl_keycard::Entity as TblKeycard;
pub use super::tbl_keycard_history::Entity as TblKeycardHistory;
pub use super::tbl_log::Entity as TblLog;
pub use super::tbl_request::Entity as TblRequest;
pub use super::tbl_request_comment::Entity as TblRequestComment;
pub use super::tbl_request_department::Entity as TblRequestDepartment;
pub use super::tbl_request_entrance::Entity as TblRequestEntrance;
pub use super::tbl_request_history::Entity as TblRequestHistory;
pub use super::tbl_role::Entity as TblRole;
pub use super::tbl_room::Entity as TblRoom;
pub use super::tbl_room_department::Entity as TblRoomDepartment;
pub use super::tbl_status::Entity as TblStatus;
pub use super::tbl_user::Entity as TblUser;
