//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "history_action")]
pub enum HistoryAction {
    #[sea_orm(string_value = "add")]
    Add,
    #[sea_orm(string_value = "change")]
    Change,
    #[sea_orm(string_value = "create")]
    Create,
    #[sea_orm(string_value = "remove")]
    Remove,
}
