//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tbl_door_group")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub door_group_id: Uuid,
    pub request_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_request_base::Entity",
        from = "Column::RequestId",
        to = "super::tbl_request_base::Column::RequestId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TblRequestBase,
    #[sea_orm(has_many = "super::tbl_door_to_group_door::Entity")]
    TblDoorToGroupDoor,
    #[sea_orm(has_many = "super::tbl_door_request::Entity")]
    TblDoorRequest,
    #[sea_orm(has_many = "super::tbl_temp_keycard_request::Entity")]
    TblTempKeycardRequest,
}

impl Related<super::tbl_request_base::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRequestBase.def()
    }
}

impl Related<super::tbl_door_to_group_door::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblDoorToGroupDoor.def()
    }
}

impl Related<super::tbl_door_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblDoorRequest.def()
    }
}

impl Related<super::tbl_temp_keycard_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTempKeycardRequest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
