//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tbl_door_to_group_door")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub door_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub door_group_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_door_group::Entity",
        from = "Column::DoorGroupId",
        to = "super::tbl_door_group::Column::DoorGroupId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TblDoorGroup,
    #[sea_orm(
        belongs_to = "super::tbl_door::Entity",
        from = "Column::DoorId",
        to = "super::tbl_door::Column::DoorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TblDoor,
}

impl Related<super::tbl_door_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblDoorGroup.def()
    }
}

impl Related<super::tbl_door::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblDoor.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
