//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use super::sea_orm_active_enums::HistoryAction;
use super::sea_orm_active_enums::HistoryRequestType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tbl_request_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub request_history_id: i64,
    pub changed_by: Uuid,
    pub request_id: Uuid,
    pub action: HistoryAction,
    pub request_type: HistoryRequestType,
    pub requester_id: Uuid,
    pub created_at: DateTime,
    pub changed_at: DateTime,
    pub active_until: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub status_id: Option<Uuid>,
    pub active: bool,
    pub accept: bool,
    pub reject: bool,
    pub pending: bool,
    pub keycard_id: Option<Uuid>,
    pub is_lost: bool,
    pub is_payed: bool,
    pub is_given_back: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_keycard::Entity",
        from = "Column::KeycardId",
        to = "super::tbl_keycard::Column::KeycardId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TblKeycard,
    #[sea_orm(has_many = "super::tbl_log::Entity")]
    TblLog,
    #[sea_orm(
        belongs_to = "super::tbl_request::Entity",
        from = "Column::RequestId",
        to = "super::tbl_request::Column::RequestId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TblRequest,
    #[sea_orm(
        belongs_to = "super::tbl_status::Entity",
        from = "Column::StatusId",
        to = "super::tbl_status::Column::StatusId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TblStatus,
    #[sea_orm(
        belongs_to = "super::tbl_user::Entity",
        from = "Column::ChangedBy",
        to = "super::tbl_user::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TblUser2,
    #[sea_orm(
        belongs_to = "super::tbl_user::Entity",
        from = "Column::RequesterId",
        to = "super::tbl_user::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TblUser1,
}

impl Related<super::tbl_keycard::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblKeycard.def()
    }
}

impl Related<super::tbl_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLog.def()
    }
}

impl Related<super::tbl_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRequest.def()
    }
}

impl Related<super::tbl_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblStatus.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
