//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tbl_request_department")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub request_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub department_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_request::Entity",
        from = "Column::RequestId",
        to = "super::tbl_request::Column::RequestId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TblRequest,
    #[sea_orm(
        belongs_to = "super::tbl_department::Entity",
        from = "Column::DepartmentId",
        to = "super::tbl_department::Column::DepartmentId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TblDepartment,
}

impl Related<super::tbl_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRequest.def()
    }
}

impl Related<super::tbl_department::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblDepartment.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
