//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tbl_request_base")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub request_id: Uuid,
    pub requester_id: Uuid,
    pub created_at: DateTime,
    pub changed_at: DateTime,
    pub active_until: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub status_id: Option<Uuid>,
    pub accept: bool,
    pub reject: bool,
    pub pending: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_user::Entity",
        from = "Column::RequesterId",
        to = "super::tbl_user::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TblUser,
    #[sea_orm(
        belongs_to = "super::tbl_status::Entity",
        from = "Column::StatusId",
        to = "super::tbl_status::Column::StatusId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TblStatus,
    #[sea_orm(has_many = "super::tbl_keycard::Entity")]
    TblKeycard,
    #[sea_orm(has_many = "super::tbl_keycard_request::Entity")]
    TblKeycardRequest,
    #[sea_orm(has_many = "super::tbl_door_group::Entity")]
    TblDoorGroup,
    #[sea_orm(has_many = "super::tbl_door_request::Entity")]
    TblDoorRequest,
    #[sea_orm(has_many = "super::tbl_request_comment::Entity")]
    TblRequestComment,
    #[sea_orm(has_many = "super::tbl_temp_keycard_request::Entity")]
    TblTempKeycardRequest,
}

impl Related<super::tbl_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblUser.def()
    }
}

impl Related<super::tbl_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblStatus.def()
    }
}

impl Related<super::tbl_keycard::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblKeycard.def()
    }
}

impl Related<super::tbl_keycard_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblKeycardRequest.def()
    }
}

impl Related<super::tbl_door_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblDoorGroup.def()
    }
}

impl Related<super::tbl_door_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblDoorRequest.def()
    }
}

impl Related<super::tbl_request_comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRequestComment.def()
    }
}

impl Related<super::tbl_temp_keycard_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTempKeycardRequest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
