//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tbl_leader")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub leader_id: Uuid,
    pub worker_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_worker::Entity",
        from = "Column::WorkerId",
        to = "super::tbl_worker::Column::WorkerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TblWorker,
}

impl Related<super::tbl_worker::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblWorker.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
