//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use super::sea_orm_active_enums::HistoryAction;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tbl_door_to_request_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub door_to_request_history_id: i64,
    pub door_id: Uuid,
    pub request_id: Uuid,
    pub action: HistoryAction,
    pub changed_by: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_request_log::Entity")]
    TblRequestLog,
}

impl Related<super::tbl_request_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRequestLog.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
