//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tbl_status")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub status_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_request::Entity")]
    TblRequest,
    #[sea_orm(has_many = "super::tbl_request_history::Entity")]
    TblRequestHistory,
}

impl Related<super::tbl_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRequest.def()
    }
}

impl Related<super::tbl_request_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRequestHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
