//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tbl_building")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub building_id: Uuid,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_room::Entity")]
    TblRoom,
    #[sea_orm(has_many = "super::tbl_request_entrance::Entity")]
    TblRequestEntrance,
}

impl Related<super::tbl_room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRoom.def()
    }
}

impl Related<super::tbl_request_entrance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRequestEntrance.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
