//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tbl_door_group")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub door_group_id: Uuid,
    pub owner_id: Uuid,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_user::Entity",
        from = "Column::OwnerId",
        to = "super::tbl_user::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TblUser,
    #[sea_orm(has_many = "super::tbl_door_to_group_door::Entity")]
    TblDoorToGroupDoor,
    #[sea_orm(has_many = "super::tbl_request::Entity")]
    TblRequest,
}

impl Related<super::tbl_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblUser.def()
    }
}

impl Related<super::tbl_door_to_group_door::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblDoorToGroupDoor.def()
    }
}

impl Related<super::tbl_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRequest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
