//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (table_name = "tbl_temp_email")] pub struct Model { # [sea_orm (primary_key)] pub email_id : i64 , # [sea_orm (column_type = "Text")] pub email_to : String , # [sea_orm (column_type = "Text")] pub email_from : String , # [sea_orm (column_type = "Text")] pub subject : String , # [sea_orm (column_type = "Text")] pub message : String , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { }

impl ActiveModelBehavior for ActiveModel { }