name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    
    runs-on: ubuntu-latest
    name: build release
    defaults:
      run:
        working-directory: .
    container:
      image: clux/muslrust
    steps:
    - uses: actions/checkout@v3
    - name: Link to predefined musl toolchain
      run: |
          ln -s /root/.cargo $HOME/.cargo
          ln -s /root/.rustup $HOME/.rustup
    
    - name: Build
      run: cargo build --release 
    - name: Print Dir
      run: |
        ls
        cd ./target/x86_64-unknown-linux-musl/release/
        ls
        mkdir ./builds
        cp ./api ./builds/api
        cp ./mock ./builds/mock
    - uses: actions/upload-artifact@v3
      with:
        name: Build test
        path: ./target/x86_64-unknown-linux-musl/release/builds